ext {
    applyAndroidConfiguration = { module, nameSpace ->

        module.configure(module) {
            apply plugin: 'com.android.library'
            apply plugin: 'org.jetbrains.kotlin.android'
            apply plugin: 'kotlin-kapt'
            apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

            android {
                namespace = nameSpace
                compileSdk = compileSdkExt

                defaultConfig {
                    minSdk = minSdkExt
                    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
                }

                buildTypes {
                    debug {
                        minifyEnabled = false
                        proguardFiles(
                                getDefaultProguardFile("proguard-android-optimize.txt"),
                                "proguard-rules.pro"
                        )
                    }

                    release {
                        minifyEnabled = true
                        proguardFiles(
                                getDefaultProguardFile("proguard-android-optimize.txt"),
                                "proguard-rules.pro"
                        )
                    }
                }

                compileOptions {
                    sourceCompatibility = javaVersionExt
                    targetCompatibility = javaVersionExt
                }

                kotlinOptions {
                    jvmTarget = jvmTargetExt
                }
            }
        }

        module.dependencies {
            implementation multidex
            implementation kotlinX
            implementation gson
        }
    }

    applyDagger = { module ->
        module.dependencies {
            implementation dagger
            kapt daggerKapt
        }
    }

    applyCompose = { module, kotlinCompile ->
        module.configure(module) {
            apply plugin: 'org.jetbrains.kotlin.plugin.compose'

            android {
                buildFeatures {
                    compose true
                }
            }
        }

        module.tasks.withType(kotlinCompile).configureEach {
            kotlinOptions {
                freeCompilerArgs += [
                        "-P",
                        "plugin:androidx.compose.compiler.plugins.kotlin:reportsDestination=" +
                                project.buildDir.absolutePath + "/compose_compiler"
                ]
                freeCompilerArgs += [
                        "-P",
                        "plugin:androidx.compose.compiler.plugins.kotlin:metricsDestination=" +
                                project.buildDir.absolutePath + "/compose_compiler"
                ]
            }
        }

        module.dependencies {
            implementation androidXComposeRuntime
            implementation androidXComposeUiWithVersions
            implementation androidXComposeFoundation
            implementation androidXComposeMaterial3WithVersion
            implementation(platform(androidXComposePlatform))
            implementation(androidXNavigation)
            implementation(androidXConstraintLayoutCompose)
            implementation(coil)
            debugImplementation(androidXComposeUiWithVersionsDebug)
        }
    }
}
