ext {
    androidXCore = [
            "androidx.core:core-ktx:$androidXCoreKtxVersion",
    ]

    androidXLifecycle = [
            "androidx.lifecycle:lifecycle-runtime-ktx:$androidXLifecycleRuntimeKtxVersion",
    ]

    androidXActivity = [
            "androidx.activity:activity-compose:$androidXActivityComposeVersion",
    ]

    androidXSecurity = [
            "androidx.security:security-crypto:$androidXSecurityVersion",
    ]

    androidXPreference = [
            "androidx.preference:preference-ktx:$androidXPreferenceVersion",
    ]

    androidXComposeUi = [
            "androidx.compose.ui:ui",
            "androidx.compose.ui:ui-graphics",
            "androidx.compose.ui:ui-tooling-preview",
    ]

    androidXComposeUiWithVersions = [
            "androidx.compose.ui:ui-graphics-android:$androidXComposeAndroidVersion",
            "androidx.compose.ui:ui-android:$androidXComposeAndroidVersion",
            "androidx.compose.ui:ui-tooling-preview:$androidXComposeAndroidVersion",
            "androidx.compose.ui:ui-tooling-preview-android:$androidXComposeAndroidVersion",
    ]

    androidXComposeUiDebug = [
            "androidx.compose.ui:ui-tooling",
    ]

    androidXComposeUiWithVersionsDebug = [
            "androidx.compose.ui:ui-tooling:$androidXComposeAndroidVersion",
    ]

    androidXComposeRuntime = [
            "androidx.compose.runtime:runtime-android:$androidXComposeAndroidVersion",
    ]

    androidXComposeFoundation = [
            "androidx.compose.foundation:foundation:$androidXComposeAndroidVersion",
            "androidx.compose.foundation:foundation-android:$androidXComposeAndroidVersion",
    ]

    androidXComposeMaterial3 = [
            "androidx.compose.material3:material3",
    ]

    androidXComposeMaterial3WithVersion = [
            "androidx.compose.material3:material3-android:$androidXMaterial3Version",
            "androidx.compose.material3:material3:$androidXMaterial3Version",
    ]

    androidXComposePlatform = "androidx.compose:compose-bom:$androidXComposeBomVersion"

    androidXNavigation = [
            "androidx.navigation:navigation-compose:$androidXNavigationComposeVersion",
    ]

    androidXConstraintLayoutCompose = [
            "androidx.constraintlayout:constraintlayout-compose:$androidXConstraintLayoutComposeVersion",
    ]

    coil = [
            "io.coil-kt:coil-compose:$coilVersion",
    ]

    kotlinX = [
            "org.jetbrains.kotlinx:kotlinx-collections-immutable:$kotlinCollectionImmutableVersion",
            "org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinXSerializationJsonVersion",
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutinesVersion",
            "org.jetbrains.kotlinx:kotlinx-coroutines-guava:$coroutinesVersion",
    ]

    androidXAppCompat = [
            "androidx.appcompat:appcompat:$androidXAppCompatVersion",
    ]

    androidXBiometric = [
            "androidx.biometric:biometric:$biometricVersion",
    ]

    androidMaterial = [
            "com.google.android.material:material:$androidMaterialVersion",
    ]

    gson = [
            "com.google.code.gson:gson:$gsonVersion",
    ]

    dagger = [
            "com.google.dagger:dagger:$daggerVersion",
            "com.google.dagger:dagger-android:$daggerVersion",
            "com.google.dagger:dagger-android-support:$daggerVersion",
    ]

    daggerKapt = [
            "com.google.dagger:dagger-compiler:$daggerVersion",
            "com.google.dagger:dagger-android-processor:$daggerVersion",
    ]

    multidex = [
            "com.android.support:multidex:$multidexVerstion"
    ]

    lifecycle = [
            "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-extensions:$lifecycleExtensionVersion",
            "androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-process:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-service:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycleVersion",
            "androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycleVersion",
    ]

    network = [
            "com.squareup.okhttp3:logging-interceptor:$okHttpVersion",
            "com.squareup.okhttp3:mockwebserver:$okHttpVersion",
            "com.squareup.retrofit2:retrofit:$retrofitVersion",
            "com.squareup.retrofit2:converter-moshi:$retrofitVersion",
            "com.squareup.retrofit2:converter-gson:$retrofitVersion",
            "com.squareup.retrofit2:converter-scalars:$retrofitVersion",
    ]

    chuckerDebug = [
            "com.github.chuckerteam.chucker:library:$chuckerVersion",
    ]

    chuckerRelease = [
            "com.github.chuckerteam.chucker:library-no-op:$chuckerVersion",
    ]

    leakCanary = [
            "com.squareup.leakcanary:leakcanary-android:$leakCanaryVersion",
    ]

    firebaseBom = "com.google.firebase:firebase-bom:$firebaseBomVersion"

    firebase = [
            "com.google.firebase:firebase-analytics",
            "com.google.firebase:firebase-messaging",
    ]
}
